#!/bin/zsh
#
# Zipped image to PDF converter (kindle optimized)
#

WD=`mktemp -d /tmp/zi2pdf.XXXXX`

function cleanup() {
	rm -rf "${WD}"
}

trap cleanup EXIT INT QUIT TERM

unzip -q "$1" -d "$WD"
for f in $WD/**/*.(jpg|jpeg|JPG|JPEG|png|PNG|bmp|BMP|gif|GIF|tiff|TIFF|tif|TIF); do
	convert -strip -geometry 560x735 -colorspace gray \
		-auto-level -gamma 0.92 -dither Riemersma \
		-colors 16 \
		"$f" "${f#.*}-tmp.png"
done

convert $WD/**/*-tmp.png "${1%.zip}.pdf"
